language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: KTl/GnVu+HhwSV55X5+n/Efru4ecVN6VKsj+gWuwHL0Q/pYs6PAP+g2lGZe2fT6/HS7IQeYfm+LsQR472SZ1Z+znQ+vE6ijQsZzkQ5pgrWuuN3dPK2o8OCYmG0lIl8YcpqRnFQmVjV+vVu8+B/NwGRoEA0MPvgdJ2GmqVmThZAss8WZ9tLEhxNmd+q7VKW1yaoxJB7T2PXHpttM7/ECLvow8DHy3PZxODkJhIyT4qncsReQUtSDnXVgLISbx84fdT5fAjeDiIFZB+k4qYRatGl+F0/mOyOUzMDrBxkYB5B57GnSYJoxoui4w/miCu6ECJeh98bDsS4Y4/SalfpJjcceHvAYEXv74hdTlltVLZgvfFXxlnLY2mMkuuSFuh/djEGV3Gdq7Y72funkLlt09DoiDEPcxmx+7BUMl3s9V4xHMgfM5u5QSDKtYwITKCwQxirjOcgl/G+i6eeR7Rdk3nuujChFUgnOG9GyGQYjlnlB+0NjtP4Gm1KfKyr4I0FqNuy7tN6I19bG8zwxPDh3Ei+nBcHdTRWea3FDRpeWC+Nzx1xstLNcs3GgaWCm4nmqASoCXNTfvZNmsiPcFz75qc1HnoXdR8HdCjN2JmEWZfGt2MoobDrGRmImLKadiS6LLLuzbtXc08IY7L/OYv5S5pneNOF7qv37xZUh44ZZyfLM=
  app: frozen-citadel-80222
