language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: of0xBWRs+kU/N/b+I5yvnRpgz6M54rhSC3V4DFsEyO5x1+o+t+qpO8rR/M8WsoGbfHGSazmWKOrbZIfxh2Ehxb3yVC+NZtqB37Ut3FwNXOKHJ5OrC2qsAh43GIc9pKq78QivTfqvI30YCjIWXOtqlTN3Uqp+sVux9bsj0CdjWprv4ypjBz4TjB43NaK6FL7GEMEpJuAOkVbKvXjPBw3OJmPhzh2LufJvSAmigR0+U54XFkzRTSZro2aRQptBl2o2kJyHckyUmI1EoUj3CJrIYIBOZZwFMjhscP/BuTBBPvnQjuAdQSXEewgeSQd6873izd2dvbtWekrnxylFRLltSLIKqQGsrzPv62pFNr4oQ5zdIpnVaaR8Yak30KcHHxX+uf245hyOfsaoAcLTbEY2+Vs63cQc6pH7ZnZdSzCEVZhKUdYgCKv9oVvKcYpQCKC6QAT+6ZI2U67E2wgKzBqGM7+tfM57Q2nyiCX0AjKU14bxDb5n+Vp4B0cJhM6gFjW5MXSJ1DPjvrJP8Fe+eH/1bmoL+JpipmiIBLAH49LL8X0n883CPFVzQpwfFkHHyn3P7d4ALj+EoP3X6xzgo8wR7YYtydagSTCmT8gcKcPPlSuwvVwWjQ/hnuqHKxc8rjn+FYvrP2VnnCN70chvEHaBViA5vG5HUuooSCQy0R+FsX0=
  app: frozen-citadel-80222
